mar7ius/simple-trip-me

Gemfile.lock, app/models/user.rb, db/migrate/20210824091807_add_long_and_lat_to_activities.rb, db/migrate/20210824092055_add_long_and_lat_to_hotels.rb, db/migrate/20210824102002_add_name_column_to_activities.rb, db/migrate/20210824102126_add_name_column_to_hotels.rb, db/migrate/20210824102304_add_compagnie_name_column_to_flights.rb, db/schema.rb, db/seeds.rb
Seed with Flight round-trip
with activities
with 3 hotels
=> completed seed

app/controllers/trips_controller.rb, db/migrate/20210825104311_change_duration_in_to_string.rb, db/schema.rb
implemented amadeus for flights @mar7ius  @DON-create-prog  !!!
=> implemented amadeus for flights

.vscode/launch.json, app/controllers/trips_controller.rb, app/views/trips/show_map.html.erb, db/seeds.rb
set up the days distribution base on driving time and activity time
=> Day calculations

public/404.html, public/500.html
=> errors 404 and 500

app/assets/stylesheets/config/_colors.scss
add 4 colors water-green; dark-green; turquoise; koral.
=> defined colors

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/config/_fonts.scss
=> font changes

app/views/trips/_day.html.erb, app/views/trips/show_map.html.erb, app/views/trips/step_one.html.erb
added bootstrap accordion and logo on departure ,arrival flight @mar7ius @DON-create-prog
=> added bootstrap accordion and logo on departure ,arrival flight

app/assets/stylesheets/components/_home.scss, app/views/pages/home.html.erb
it was used all over as a bootstrap class. Renamed to banner-block-text, as weel as adding bootstrap container class to keep properties
=> renamed class container used in home.scss 

app/assets/stylesheets/components/_cards_flights.scss, app/assets/stylesheets/components/_home.scss, app/views/pages/home.html.erb, app/views/trips/_flight_ticket_info.html.erb, app/views/trips/step_one.html.erb
=> Fix flight layout

app/assets/stylesheets/components/_cards_flights.scss
changed svg call in css @mar7ius
=>  changed svg call in css

db/seeds.rb
Changed seed by removing Flights and Hotels
=> changing seeds - removed Hotels and Flights

app/assets/stylesheets/components/_map.scss, app/views/trips/_day.html.erb, app/views/trips/show_map.html.erb
adjusted the map size towards the left, and put space around the activity display in the accordion
=> adjusted the map 

app/assets/stylesheets/components/_content_wrapper.scss, app/views/layouts/application.html.erb
fix wrapper margin top and bottom
=> fix wrapper around the yield

app/assets/stylesheets/components/_cards.scss, app/views/trips/_activity_infos.html.erb, db/seeds.rb
Instead of putting a modal we put a hoover (seen with Florent). changed the seed for more uniform description.
=> fix hoover ans seed

app/models/activity.rb, app/views/trips/_activity_infos.html.erb, public/404.html
fix time's activity : hour + min (if <0)
remove icone $
change image in 404 (jpg-->png because in the html it was noted png or in images folder in jpg)
=> fix duration h min

app/assets/stylesheets/components/_cards.scss, app/views/trips/_activity_infos.html.erb
fix line clamp instead of truncate in card activity.
=> fix line-clamp

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/vendors/_index.scss, app/assets/stylesheets/vendors/_masonry.scss, app/javascript/controllers/masonry_controller.js, app/views/trips/_activity_infos.html.erb, app/views/trips/step_two.html.erb
add effect loaded on cards activity (with grid + js)
=> add effect on cards activity

app/assets/stylesheets/components/_content_wrapper.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/pages/dashboard.html.erb
fix footer with main wrapper (div ) login, sign in
=> add wrapper on missing pages

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_map.scss, app/views/trips/_day.html.erb, app/views/trips/show_map.html.erb
last modifs of front on the map display page @mar7ius @fhorta28  @DON-create-prog
=> last modifs of front on the map display page

app/views/shared/_navbar.html.erb
space on Home, dashboard and my account in navbar
=> space in navbar

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/vendors/_masonry.scss, app/javascript/controllers/masonry_controller.js, app/views/trips/_day.html.erb, app/views/trips/show_map.html.erb
remove "animate" on datepicker
resize card
resize price summary
=> corrections vu avec Florent

app/views/shared/_navbar.html.erb
fix space between Home Dashboard My account in the navbar: less padding
=> fix space between Home Dashboard My account in the navbar
